IF "%BUILD_DIR%"=="" GOTO :EOF
IF NOT EXIST "%BUILD_DIR%" GOTO :EOF
RD /S /Q "%BUILD_DIR%"

IF "%BUILD_DIR_TEAM%"=="" GOTO :EOF
IF NOT EXIST "%BUILD_DIR_TEAM%" GOTO :EOF
RD /S /Q "%BUILD_DIR_TEAM%"

exit /B 0